In [5]:
import numpy as np

In [6]:
h = np.zeros((2, 2), dtype=np.uint8)

In [7]:
def history_add(value):
        v = np.array(value, dtype=np.uint8)
        h[1:] = h[:-1]
        h[0] = v

In [8]:
h[0] = [-1, 1]
print(h)

[[255   1]
 [  0   0]]


In [9]:
history_add([1, 1])
print(h)

[[  1   1]
 [255   1]]


In [10]:
history_add([2, 2])
print(h)

[[2 2]
 [1 1]]


In [12]:
print(h[0])

[2 2]
