In [2]:
import numpy as np
import time
from PreProcess import *

In [43]:
def closest_anchor_map(x, y,
                       image_width, image_height,
                       anchor_width, anchor_height,
                       offset_scale):
    """ Create a anchor_height x anchor_width x 3 map.
        First entry is 1 if the anchor point is closest to true point. Zero otherwise.
        Second is x offset.
        Third is y offset. """
    anchor_coords = get_anchors(image_width, image_height, anchor_width, anchor_height)

    x_limit = image_width / anchor_width
    y_limit = image_height / anchor_height
    dist_limit = np.sqrt(x_limit**2 + y_limit**2)

    res = np.zeros((anchor_width, anchor_height, 3))

    if x is not None and y is not None and x > 0 and y > 0:
        xs = anchor_coords[:, :, 0]
        ys = anchor_coords[:, :, 1]
        dist_matrix = np.sqrt( (xs - x)**2 + (ys - y)**2 )
        min_val = np.min(dist_matrix)
        closest_xs, closest_ys = np.where(dist_matrix<=dist_limit)
        
        # Set offsets
        for cx, cy in zip(closest_xs, closest_ys):
            #print(f"(cx, cy): ({cx}, {cy})")
            anchor_x, anchor_y = anchor_coords[cx, cy]
            closest_offset_x = (x - anchor_x) / offset_scale
            closest_offset_y = (y - anchor_y) / offset_scale
            res[cx, cy, 1:] = (closest_offset_x, closest_offset_y)
        
        # Set label
        closest_x, closest_y = np.where(dist_matrix==min_val)
        closest_x = closest_x[0]  # If multiple values, the first one is used
        closest_y = closest_y[0]
        res[closest_x, closest_y, 0] = 1
        
    
    return res


cam = closest_anchor_map(2, 2, 5, 5, 3, 3, 1.0)
print(cam)

dist_limit: 2.3570226039551585
[[[ 0.  1.  1.]
  [ 0.  1.  0.]
  [ 0.  1. -1.]]

 [[ 0.  0.  1.]
  [ 1.  0.  0.]
  [ 0.  0. -1.]]

 [[ 0. -1.  1.]
  [ 0. -1.  0.]
  [ 0. -1. -1.]]]
