In [13]:
import numpy as np
from scipy.spatial import KDTree

In [25]:
points1 = np.random.randint(low=0, high=10, size=(10, 3))
points2 = np.random.randint(low=0, high=10, size=(10, 3))
print(points)

[[0 6 5]
 [6 1 5]
 [6 1 6]
 [7 4 2]
 [2 5 0]
 [8 9 9]
 [8 9 5]
 [0 7 3]
 [2 9 2]
 [5 9 4]]


In [48]:
t1 = np.array([1, 2, 3])
t2 = np.array([3, 2, 1])
s = np.sqrt(np.sum((t1 - t2)**2))
print(s)

2.8284271247461903


In [54]:
def distance_from(ps, x):
    for p in ps:
        r = np.sqrt(np.sum((p - x)**2))
        print(r)

In [26]:
kd_tree1 = KDTree(points1, leafsize=3)
kd_tree2 = KDTree(points2, leafsize=3)

In [35]:
kd_tree1.count_neighbors(kd_tree2, 4)

11

In [60]:
test_point = np.array([0, 0, 0])
kd_tree1.query_ball_point(test_point, 9)

[3, 4]

In [55]:
distance_from(points1, test_point)

14.45683229480096
9.539392014169456
11.357816691600547
5.830951894845301
8.54400374531753
13.856406460551018
12.041594578792296
11.090536506409418
14.45683229480096
10.0


In [62]:
kd_tree1.query_ball_tree(kd_tree2, 2)

[[], [], [6], [1], [], [], [], [], [], []]