In [14]:
import numpy as np
import vtk
from vtk.util import numpy_support

In [3]:
np.random.rand(3)

array([0.74509331, 0.40514182, 0.23229616])

In [22]:
points = np.zeros((2, 3))
print(points)
for i in range(2):
    points[i] = 20*(np.random.rand(3)-0.5)
print(points)

[[0. 0. 0.]
 [0. 0. 0.]]
[[-2.19336289  1.18899401 -4.10135012]
 [-3.20486487 -1.45474461  7.10648846]]


```
vtkFloatArray (0x7f65dc414870)
  Debug: Off
  Modified Time: 67741
  Reference Count: 2
  Registered Events: (none)
  Name: Points
  Data type: float
  Size: 24573
  MaxId: 16673
  NumberOfComponents: 3
  Information: 0x7f65dc4144a0
    Debug: Off
    Modified Time: 67740
    Reference Count: 1
    Registered Events: (none)
  Name: Points
  Number Of Components: 3
  Number Of Tuples: 5558
  Size: 24573
  MaxId: 16673
  LookupTable: (none)
```

In [27]:
points_vtk = numpy_support.numpy_to_vtk(points.ravel(), deep=True, array_type=vtk.VTK_FLOAT)

/home/clh/anaconda3/lib/python3.6/site-packages/vtk/util/numpy_support.py:137: FutureWarning: Conversion of the second argument of issubdtype from `complex` to `np.complexfloating` is deprecated. In future, it will be treated as `np.complex128 == np.dtype(complex).type`.
  assert not numpy.issubdtype(z.dtype, complex), \


In [28]:
print(points_vtk)

vtkFloatArray (0x563d533cdc90)
  Debug: Off
  Modified Time: 110
  Reference Count: 1
  Registered Events: (none)
  Name: (none)
  Data type: float
  Size: 6
  MaxId: 5
  NumberOfComponents: 1
  Information: 0
  Name: (none)
  Number Of Components: 1
  Number Of Tuples: 6
  Size: 6
  MaxId: 5
  LookupTable: (none)


